//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }
    
        public long ID_tovar { get; set; }
        public Nullable<long> ID_kategory { get; set; }
        public string Artikul { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<double> OptCena { get; set; }
        public Nullable<double> RoznCena { get; set; }
        public Nullable<long> Ostatok { get; set; }
    
        public virtual Kategory Kategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
